# permissions for end users to view podapps.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: podapp-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: operator2
    app.kubernetes.io/part-of: operator2
    app.kubernetes.io/managed-by: kustomize
  name: podapp-viewer-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - podapps
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - app.example.com
  resources:
  - podapps/status
  verbs:
  - get
