---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - app.example.com
  resources:
  - podapps
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - app.example.com
  resources:
  - podapps/finalizers
  verbs:
  - update
- apiGroups:
  - app.example.com
  resources:
  - podapps/status
  verbs:
  - get
  - patch
  - update
